# Generated by Django 6.0.3 on 2026-03-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorant_uuid', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('display_icon', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
